"""add bot table_2

Revision ID: 348c3fe6d30b
Revises: 2117c45dc426
Create Date: 2024-04-18 11:10:43.900854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '348c3fe6d30b'
down_revision: Union[str, None] = '2117c45dc426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rcs_bot',
    sa.Column('bot', postgresql.ENUM('YollaGoogle', 'YollaSinch', name='rcsbot'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_update', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rcs_bot')
    # ### end Alembic commands ###
