"""add task relationship and change task column name

Revision ID: 86c29616ab26
Revises: 502c766c20f3
Create Date: 2024-04-12 12:10:45.989890

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '86c29616ab26'
down_revision: Union[str, None] = '502c766c20f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_result', sa.Column('task_id', sa.Integer(), nullable=True))
    op.drop_constraint('task_result_task_fkey', 'task_result', type_='foreignkey')
    op.create_foreign_key(None, 'task_result', 'task', ['task_id'], ['id'])
    op.drop_column('task_result', 'task')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_result', sa.Column('task', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'task_result', type_='foreignkey')
    op.create_foreign_key('task_result_task_fkey', 'task_result', 'task', ['task'], ['id'])
    op.drop_column('task_result', 'task_id')
    # ### end Alembic commands ###
